    LIST p=16F887
    #include "p16f887.inc"

    __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

CBLOCK 0x70
    W_TEMP
    STATUS_TEMP
ENDC

CBLOCK 0x20
    TEMP
    TEMP_UART
    ADCVAL
    CENTENA
    DECENA
    UNIDAD
    CONT1
    CONT3
    RXDATO
    PATRON_DECENA
    PATRON_UNIDAD
    DISPLAY_ACTIVO
ENDC

    ORG 0x00
    GOTO INICIO

    ORG 0x04
    GOTO ISR

    ORG 0x05

INICIO
    BANKSEL ANSEL
    MOVLW b'00000001'
    MOVWF ANSEL
    CLRF ANSELH

    BANKSEL PORTC
    CLRF PORTC
    BSF PORTC,0
    BSF PORTC,1

    BANKSEL PORTD
    MOVLW b'11111111'
    MOVWF PORTD

    BANKSEL TRISA
    BSF TRISA,0

    BANKSEL TRISC
    BCF TRISC,0
    BCF TRISC,1
    BCF TRISC,2
    BCF TRISC,3
    BCF TRISC,6
    BSF TRISC,7

    BANKSEL TRISD
    CLRF TRISD

    ; UART 9600 @ 4MHz
    BANKSEL TXSTA
    MOVLW b'00100100'
    MOVWF TXSTA

    BANKSEL RCSTA
    MOVLW b'10010000'
    MOVWF RCSTA

    BANKSEL SPBRG
    MOVLW .25
    MOVWF SPBRG

    ; ADC
    BANKSEL ADCON1
    MOVLW b'00000000'
    MOVWF ADCON1

    BANKSEL ADCON0
    MOVLW b'01000001'
    MOVWF ADCON0

    ; VARIABLES
    BANKSEL TEMP
    CLRF TEMP
    CLRF TEMP_UART
    CLRF DECENA
    CLRF UNIDAD
    CLRF DISPLAY_ACTIVO

    MOVLW b'11111111'
    MOVWF PATRON_DECENA
    MOVWF PATRON_UNIDAD

    ; TIMER0 + ISR
    ; Prescaler 1:32
  
    BANKSEL OPTION_REG
    MOVLW b'00000100'
    MOVWF OPTION_REG

    BANKSEL TMR0
    MOVLW .100
    MOVWF TMR0

    BANKSEL INTCON
    BCF INTCON,T0IF
    BSF INTCON,T0IE
    BSF INTCON,GIE

MAIN
    CALL LEER_ADC

    MOVF ADCVAL,W
    MOVWF TEMP
    BCF STATUS,C
    RLF TEMP,F

    MOVF TEMP,W
    MOVWF TEMP_UART

    ; Enviar temperatura ASCII a la interfaz
    MOVF TEMP_UART,W
    CALL ENVIA_DECIMAL
    CALL CRLF

    ; ENVIA_DECIMAL deja DECENA y UNIDAD calculadas
    ; Ahora preparar patrones para que la ISR solo los muestre
    MOVF DECENA,W
    CALL TABLA_7SEG
    MOVWF PATRON_DECENA

    MOVF UNIDAD,W
    CALL TABLA_7SEG
    MOVWF PATRON_UNIDAD

    CALL DELAY_1S_UART

    GOTO MAIN

; ISR TIMER0

ISR
    MOVWF W_TEMP
    SWAPF STATUS,W
    MOVWF STATUS_TEMP

    BANKSEL INTCON
    BTFSS INTCON,T0IF
    GOTO ISR_FIN

    BCF INTCON,T0IF

    BANKSEL TMR0
    MOVLW .100
    MOVWF TMR0

    ; Apagar ambos displays antes de cambiar segmentos
    BANKSEL PORTC
    BSF PORTC,0
    BSF PORTC,1

    BANKSEL DISPLAY_ACTIVO
    BTFSS DISPLAY_ACTIVO,0
    GOTO ISR_DECENA
    GOTO ISR_UNIDAD

ISR_DECENA
    MOVF PATRON_DECENA,W
    BANKSEL PORTD
    MOVWF PORTD

    BANKSEL PORTC
    BCF PORTC,0          ; prende decenas

    BANKSEL DISPLAY_ACTIVO
    BSF DISPLAY_ACTIVO,0
    GOTO ISR_FIN

ISR_UNIDAD
    MOVF PATRON_UNIDAD,W
    BANKSEL PORTD
    MOVWF PORTD

    BANKSEL PORTC
    BCF PORTC,1          ; prende unidades

    BANKSEL DISPLAY_ACTIVO
    BCF DISPLAY_ACTIVO,0

ISR_FIN
    SWAPF STATUS_TEMP,W
    MOVWF STATUS
    SWAPF W_TEMP,F
    SWAPF W_TEMP,W
    RETFIE


; LEER ADC

LEER_ADC
    CALL DELAY_ADC

    BANKSEL ADCON0
    BSF ADCON0,GO_DONE

ESPERA_ADC
    BTFSC ADCON0,GO_DONE
    GOTO ESPERA_ADC

    BANKSEL ADRESH
    MOVF ADRESH,W

    BANKSEL ADCVAL
    MOVWF ADCVAL
    RETURN


; TABLA 7 SEGMENTOS
; Ánodo común, RD2 siempre en 1

TABLA_7SEG
    ADDWF PCL,F
    RETLW b'10000100'      ; 0
    RETLW b'11110101'      ; 1
    RETLW b'01001100'      ; 2
    RETLW b'01100100'      ; 3
    RETLW b'00110101'      ; 4
    RETLW b'00100110'      ; 5
    RETLW b'00000110'      ; 6
    RETLW b'11110100'      ; 7
    RETLW b'00000100'      ; 8
    RETLW b'00100100'      ; 9


; UART TX

UART_TX
    BANKSEL PIR1
TX_WAIT
    BTFSS PIR1,TXIF
    GOTO TX_WAIT

    BANKSEL TXREG
    MOVWF TXREG
    RETURN


; ENVIA DECIMAL ASCII
; Entrada W = temperatura
; Salida UART: dos dígitos + CRLF externo
; También deja DECENA y UNIDAD listas

ENVIA_DECIMAL
    BANKSEL TEMP
    MOVWF TEMP
    CLRF CENTENA
    CLRF DECENA

C100
    MOVLW .100
    SUBWF TEMP,W
    BTFSS STATUS,C
    GOTO C10
    MOVWF TEMP
    INCF CENTENA,F
    GOTO C100

C10
    MOVLW .10
    SUBWF TEMP,W
    BTFSS STATUS,C ;carry 0 es neg
    GOTO FIN10
    MOVWF TEMP
    INCF DECENA,F
    GOTO C10

FIN10
    MOVF TEMP,W
    MOVWF UNIDAD

    MOVF DECENA,W
    ADDLW '0'
    CALL UART_TX

    MOVF UNIDAD,W
    ADDLW '0'
    CALL UART_TX

    RETURN

CRLF
    MOVLW .13
    CALL UART_TX
    MOVLW .10
    CALL UART_TX
    RETURN


; UART RX / COMANDOS
; 0x00 cooler off
; 0x01 cooler on
; 0x02 lámpara on
; 0x03 lámpara off

REVISAR_UART
    BANKSEL RCSTA
    BTFSS RCSTA,OERR
    GOTO RX_NORMAL

    BCF RCSTA,CREN
    BSF RCSTA,CREN

RX_NORMAL
    BANKSEL PIR1
    BTFSS PIR1,RCIF
    RETURN
;;;;;;;;;;;;
    BANKSEL RCREG
    MOVF RCREG,W

    BANKSEL RXDATO
    MOVWF RXDATO

    MOVF RXDATO,W
    XORLW .0
    BTFSC STATUS,Z
    GOTO COOLER_OFF

    MOVF RXDATO,W
    XORLW .1
    BTFSC STATUS,Z
    GOTO COOLER_ON

    MOVF RXDATO,W
    XORLW .2
    BTFSC STATUS,Z
    GOTO LAMPARA_ON

    MOVF RXDATO,W
    XORLW .3
    BTFSC STATUS,Z
    GOTO LAMPARA_OFF

    RETURN

COOLER_OFF
    BANKSEL PORTC
    BCF PORTC,2
    RETURN

COOLER_ON
    BANKSEL PORTC
    BSF PORTC,2
    RETURN

LAMPARA_ON
    BANKSEL PORTC
    BSF PORTC,3
    RETURN

LAMPARA_OFF
    BANKSEL PORTC
    BCF PORTC,3
    RETURN


DELAY_ADC
    NOP
    NOP
    NOP
    NOP
    NOP
    RETURN

DELAY_1S_UART
    MOVLW .250
    MOVWF CONT1

D1
    CALL REVISAR_UART
    CALL DELAY_CORTO
    DECFSZ CONT1,F
    GOTO D1

    RETURN

DELAY_CORTO
    MOVLW .255
    MOVWF CONT3

DC1
    DECFSZ CONT3,F
    GOTO DC1
    RETURN

    END